export const banks = [
    { value: "Ngân hàng Vietcombank", label: "Ngân hàng Vietcombank" },
    { value: "Ngân hàng Agribank", label: "Ngân hàng Agribank" },
    { value: "Ngân hàng BIDV", label: "Ngân hàng BIDV" },
    { value: "Ngân hàng VietinBank", label: "Ngân hàng VietinBank" },
    { value: "Ngân hàng Á Châu (ACB)", label: "Ngân hàng Á Châu (ACB)" },
    { value: "Ngân hàng An Bình (ABBank)", label: "Ngân hàng An Bình (ABBank)" },
    { value: "Ngân hàng Bắc Á (Bac A Bank)", label: "Ngân hàng Bắc Á (Bac A Bank)" },
    { value: "Ngân hàng Bản Việt (Viet Capital Bank)", label: "Ngân hàng Bản Việt (Viet Capital Bank)" },
    { value: "Ngân hàng Bảo Việt (BAOVIET Bank)", label: "Ngân hàng Bảo Việt (BAOVIET Bank)" },
    { value: "Ngân hàng Bưu điện Liên Việt (LienVietPostBank)", label: "Ngân hàng Bưu điện Liên Việt (LienVietPostBank)" },
    { value: "Ngân hàng Công thương Việt Nam (VietinBank)", label: "Ngân hàng Công thương Việt Nam (VietinBank)" },
    { value: "Ngân hàng Đại Chúng Việt Nam (PVcomBank)", label: "Ngân hàng Đại Chúng Việt Nam (PVcomBank)" },
    { value: "Ngân hàng Đông Á (DongA Bank)", label: "Ngân hàng Đông Á (DongA Bank)" },
    { value: "Ngân hàng Đông Nam Á (SeABank)", label: "Ngân hàng Đông Nam Á (SeABank)" },
    { value: "Ngân hàng Hàng Hải (MSB)", label: "Ngân hàng Hàng Hải (MSB)" },
    { value: "Ngân hàng Kiên Long (Kienlongbank)", label: "Ngân hàng Kiên Long (Kienlongbank)" },
    { value: "Ngân hàng Kỹ Thương (Techcombank)", label: "Ngân hàng Kỹ Thương (Techcombank)" },
    { value: "Ngân hàng Nam Á (Nam A Bank)", label: "Ngân hàng Nam Á (Nam A Bank)" },
    { value: "Ngân hàng Phương Đông (OCB)", label: "Ngân hàng Phương Đông (OCB)" },
    { value: "Ngân hàng Quân Đội (MB)", label: "Ngân hàng Quân Đội (MB)" },
    { value: "Ngân hàng Quốc Tế (VIB)", label: "Ngân hàng Quốc Tế (VIB)" },
    { value: "Ngân hàng Sài Gòn (SCB)", label: "Ngân hàng Sài Gòn (SCB)" },
    { value: "Ngân hàng Sài Gòn – Hà Nội (SHB)", label: "Ngân hàng Sài Gòn – Hà Nội (SHB)" },
    { value: "Ngân hàng Sài Gòn Công Thương (SAIGONBANK)", label: "Ngân hàng Sài Gòn Công Thương (SAIGONBANK)" },
    { value: "Ngân hàng Sài Gòn Thương Tín (Sacombank)", label: "Ngân hàng Sài Gòn Thương Tín (Sacombank)" },
    { value: "Ngân hàng Tiên Phong (TPBank)", label: "Ngân hàng Tiên Phong (TPBank)" },
    { value: "Ngân hàng Việt Á (VietABank)", label: "Ngân hàng Việt Á (VietABank)" },
    { value: "Ngân hàng Việt Nam Thịnh Vượng (VPBank)", label: "Ngân hàng Việt Nam Thịnh Vượng (VPBank)" },
    { value: "Ngân hàng Việt Nam Thương Tín (Vietbank)", label: "Ngân hàng Việt Nam Thương Tín (Vietbank)" },
    { value: "Ngân hàng Xăng dầu Petrolimex (PG Bank)", label: "Ngân hàng Xăng dầu Petrolimex (PG Bank)" },
    { value: "Ngân hàng Xuất Nhập Khẩu (Eximbank)", label: "Ngân hàng Xuất Nhập Khẩu (Eximbank)" },
    { value: "Ngân hàng TNHH Indovina (IVB)", label: "Ngân hàng TNHH Indovina (IVB)" },
    { value: "Ngân hàng Liên doanh Việt Nga (VRB)", label: "Ngân hàng Liên doanh Việt Nga (VRB)" },
    { value: "Ngân hàng ANZ Việt Nam (ANZ)", label: "Ngân hàng ANZ Việt Nam (ANZ)" },
    { value: "Ngân hàng Hong Leong Việt Nam (HLB)", label: "Ngân hàng Hong Leong Việt Nam (HLB)" },
    { value: "Ngân hàng HSBC Việt Nam (HSBC)", label: "Ngân hàng HSBC Việt Nam (HSBC)" },
    { value: "Ngân hàng Shinhan Việt Nam (Shinhan)", label: "Ngân hàng Shinhan Việt Nam (Shinhan)" },
    { value: "Ngân hàng Standard Chartered Việt Nam (SCBVL)", label: "Ngân hàng Standard Chartered Việt Nam (SCBVL)" },
    { value: "Ngân hàng Public Bank Việt Nam (PBVN)", label: "Ngân hàng Public Bank Việt Nam (PBVN)" },
    { value: "Ngân hàng CIMB Việt Nam (CIMB)", label: "Ngân hàng CIMB Việt Nam (CIMB)" },
    { value: "Ngân hàng Woori Việt Nam (Woori)", label: "Ngân hàng Woori Việt Nam (Woori)" },
    { value: "Ngân hàng UOB Việt Nam (UOB)", label: "Ngân hàng UOB Việt Nam (UOB)" }
  ];